# Generated by Django 5.2.4 on 2025-07-04 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontime_app.clase'),
        ),
    ]
