# Generated by Django 5.2.1 on 2025-06-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0002_alter_usuariopersonalizado_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
