# Generated by Django 5.2.4 on 2025-07-04 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0002_alter_asistencia_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Inasistencia', 'Inasistencia'), ('Justificativo', 'Justificativo'), ('Retardo', 'Retardo'), ('Otro', 'Otro')], max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Vista', 'Vista'), ('Resuelta', 'Resuelta')], default='Pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
