# Generated by Django 5.2.1 on 2025-06-11 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0005_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('medico', 'Médico'), ('personal', 'Personal'), ('familia', 'Familiar'), ('otro', 'Otro')], max_length=20)),
                ('fecha_ausencia', models.DateField()),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='justificativos/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
