# Generated by Django 5.2.1 on 2025-06-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0007_clase_asistencia_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='clase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ontime_app.clase'),
        ),
    ]
