# Generated by Django 5.2.1 on 2025-06-19 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0009_codigogenerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigogenerado',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ontime_app.clase'),
        ),
    ]
