# Generated by Django 5.2.1 on 2025-06-20 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0010_codigogenerado_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontime_app.clase'),
        ),
    ]
