# Generated by Django 5.2.1 on 2025-06-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0011_usuariopersonalizado_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='grupo',
            field=models.CharField(default=3069239, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clase',
            name='tipo',
            field=models.CharField(choices=[('tecnica', 'Técnica'), ('complementaria', 'Complementaria')], default='Técnica', max_length=20),
            preserve_default=False,
        ),
    ]
