# Generated by Django 5.2.1 on 2025-06-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0012_clase_grupo_clase_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='clase',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='clases',
            field=models.ManyToManyField(blank=True, to='ontime_app.clase'),
        ),
    ]
