# Generated by Django 5.2.1 on 2025-06-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0013_remove_usuariopersonalizado_clase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='clases_dictadas',
            field=models.ManyToManyField(blank=True, related_name='instructores', to='ontime_app.clase'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='clases',
            field=models.ManyToManyField(blank=True, related_name='aprendices', to='ontime_app.clase'),
        ),
    ]
