# Generated by Django 5.2.1 on 2025-06-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0014_usuariopersonalizado_clases_dictadas_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('nombre', 'grupo')},
        ),
    ]
