# Generated by Django 5.2.1 on 2025-06-27 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0017_competencia_clase_competencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
