# Generated by Django 5.2.1 on 2025-07-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0019_mensajecontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
