# Generated by Django 5.2.1 on 2025-07-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime_app', '0020_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='categoria',
            field=models.CharField(choices=[('cuenta', 'Cuenta'), ('asistencia', 'Asistencia'), ('qr', 'QR'), ('reportes', 'Reportes'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
